#!/usr/bin/env node
import crypto from 'node:crypto';
import fs from 'node:fs';
import path from 'node:path';
import { loadRows, parseArgs } from './lib/data.mjs';

const args=parseArgs(process.argv.slice(2));if(!args._.length||!args.output){console.error('Usage: node normalize_data.mjs INPUT [INPUT ...] --output normalized-dataset.jsonl [--manifest dataset-manifest.json] [--source-snapshot PROFILE_SHA256] [--table-id observations] [--observation-unit record] [--sheet 0] [--entity-key noteId] [--canonical-policy keep-all|first|group-entity]');process.exit(2)}
try{
  const inputs=args._.map(value=>path.resolve(value)),sources=inputs.map((input,source_index)=>{const rows=loadRows(input,{sheet:args.sheet??0}),hash=crypto.createHash('sha256').update(fs.readFileSync(input)).digest('hex');return {input,rows,hash,bytes:fs.statSync(input).size,source_index,source_group:path.basename(input,path.extname(input))}});
  if(sources.some(s=>!s.rows.length))throw new Error('Every input must contain at least one row.');
  const seen=new Set(),normalized=sources.flatMap(source=>source.rows.map((row,index)=>{const clean=Object.fromEntries(Object.entries(row).map(([k,v])=>[String(k).trim(),typeof v==='string'?v.trim():v]));const base=`${source.source_index}:${source.hash}:${args.sheet??0}:${index+1}`,rowId=`r_${crypto.createHash('sha256').update(base).digest('hex').slice(0,16)}`;if(seen.has(rowId))throw new Error(`Duplicate row_id ${rowId}`);seen.add(rowId);return {row_id:rowId,source_file:source.input,source_group:source.source_group,source_row:index+2,...clean}}));
  const entityKey=args['entity-key'],policy=args['canonical-policy']??'keep-all';if(!['keep-all','first','group-entity'].includes(policy))throw new Error('canonical-policy must be keep-all, first, or group-entity.');
  const duplicateSummary={entity_key:entityKey??null,policy,total_rows:normalized.length,unique_entities:null,duplicate_rows:0};
  if(entityKey){const counts=new Map();for(const row of normalized){const id=String(row[entityKey]??'').trim();if(!id)continue;counts.set(id,(counts.get(id)??0)+1)}duplicateSummary.unique_entities=counts.size;duplicateSummary.duplicate_rows=[...counts.values()].reduce((n,c)=>n+Math.max(0,c-1),0);const canonicalSeen=new Set();for(const row of normalized){const id=String(row[entityKey]??'').trim(),key=policy==='group-entity'?`${row.source_group}\u0000${id}`:id;row.duplicate_entity=id?((counts.get(id)??0)>1):false;row.canonical_sample=policy==='keep-all'||!id||!canonicalSeen.has(key);if(id)canonicalSeen.add(key)}}else for(const row of normalized)row.canonical_sample=true;
  const out=path.resolve(args.output);fs.mkdirSync(path.dirname(out),{recursive:true});fs.writeFileSync(out,normalized.map(r=>JSON.stringify(r)).join('\n')+'\n','utf8');
  const combinedHash=crypto.createHash('sha256').update(sources.map(s=>`${s.source_index}:${s.input}:${s.hash}`).join('\n')).digest('hex'),outputHash=crypto.createHash('sha256').update(fs.readFileSync(out)).digest('hex');
  const audit={schema_version:'1.1',inputs:sources.map(({input,hash,bytes,source_index,source_group,rows})=>({input,snapshot_sha256:hash,bytes,source_index,source_group,row_count:rows.length})),combined_snapshot_sha256:combinedHash,sheet:args.sheet??0,row_count:normalized.length,row_id_rule:'sha256(source_index:source_hash:sheet:data_row_index)[0:16]',duplicate_summary:duplicateSummary,canonical_sample_rule:policy,output:out,generated_at:new Date().toISOString()};fs.writeFileSync(`${out}.audit.json`,JSON.stringify(audit,null,2)+'\n','utf8');
  const sourceSnapshot=args['source-snapshot']??combinedHash;if(!/^[a-f0-9]{64}$/.test(sourceSnapshot))throw new Error('--source-snapshot must be a 64-character lowercase SHA-256.');
  const manifest={schema_version:'1.0',source_snapshot_sha256:sourceSnapshot,tables:[{table_id:args['table-id']??'observations',path:path.relative(path.dirname(path.resolve(args.manifest??path.join(path.dirname(out),'dataset-manifest.json'))),out)||path.basename(out),sha256:outputHash,row_count:normalized.length,observation_unit:args['observation-unit']??'record'}]};const manifestPath=path.resolve(args.manifest??path.join(path.dirname(out),'dataset-manifest.json'));fs.writeFileSync(manifestPath,JSON.stringify(manifest,null,2)+'\n','utf8');console.log(`Normalized ${normalized.length} rows from ${sources.length} input(s); canonical policy=${policy}, duplicate rows=${duplicateSummary.duplicate_rows} -> ${out}; manifest -> ${manifestPath}`);
}catch(error){console.error(error.message);process.exit(1)}
