#!/usr/bin/env node
import fs from 'node:fs';import os from 'node:os';import path from 'node:path';import crypto from 'node:crypto';import {spawnSync} from 'node:child_process';import {fileURLToPath} from 'node:url';
const root=path.dirname(path.dirname(fileURLToPath(import.meta.url))),temp=fs.mkdtempSync(path.join(os.tmpdir(),'quanti-chart-test-')),fx=n=>path.join(root,'evals/fixtures',n),sha=t=>crypto.createHash('sha256').update(t).digest('hex');
const spec=JSON.parse(fs.readFileSync(fx('smoke-report-spec.json'),'utf8')),results=JSON.parse(fs.readFileSync(fx('smoke-analysis-results.json'),'utf8')),findings=JSON.parse(fs.readFileSync(fx('smoke-findings-ledger.json'),'utf8'));spec.tier='quick';
const guide={focus:'先看重点标记。',comparison:'在共同尺度上比较项目。',signal:'视觉差异对应标题中的关系。'};
const source=[
 ['dot',[{label:'A',value:12,highlight:true},{label:'B',value:8}]],['diverging-bar',[{label:'A',value:-12},{label:'B',value:18,highlight:true}]],['scatter',[{label:'A',x:12,y:18,highlight:true},{label:'B',x:8,y:11}]],['dumbbell',[{label:'A',start:8,end:12},{label:'B',start:11,end:18}]],['normalized-stacked-bar',[{label:'A',segments:[{label:'X',value:7},{label:'Y',value:3}]},{label:'B',segments:[{label:'X',value:4},{label:'Y',value:6}]}]],['heatmap',[{row:'A',column:'X',value:7},{row:'A',column:'Y',value:3},{row:'B',column:'X',value:4},{row:'B',column:'Y',value:6}]],['histogram',[1,2,2,3,4,8,13].map((value,i)=>({label:String(i),value}))],['box',[{label:'A',low:2,mid:5,high:9},{label:'B',low:3,mid:7,high:12}]],['quadrant',[{label:'A',x:2,y:8,size:20,highlight:true},{label:'B',x:7,y:4,size:10}]]
];
const charts=source.map(([type,value],i)=>{const id=`chart-series-${i+1}`;results.results[id]={contract_id:'channel-volume',kind:'series',value};return {type,title:type,view_id:`chart-view-${i+1}`,reading_guide:guide,result_refs:['a-notes'],data_ref:id,source:'fixture',denominator:'test',digits:1}});
findings.findings.push({finding_id:'chart-regression-finding',type:'fact',title:'图表 fixture 验证关系型图表',text:'本章仅验证图表渲染。',result_refs:source.map((_,i)=>`chart-series-${i+1}`),evidence_level:'descriptive',robustness_status:'passed',source:'fixture',limitations:[]});
spec.sections.push({id:'appendix-charts',judgment_id:'sensitivity-judgment',title:'B 渠道的高互动集中在 3 月单点，现有均值不足以支持渠道优劣排名',appendix:true,finding_refs:['chart-regression-finding'],charts});
const specPath=path.join(temp,'spec.json'),resultsPath=path.join(temp,'results.json'),findingsPath=path.join(temp,'findings.json'),htmlPath=path.join(temp,'report.html');for(const [p,v] of [[specPath,spec],[resultsPath,results],[findingsPath,findings]])fs.writeFileSync(p,JSON.stringify(v));
const r=spawnSync(process.execPath,[path.join(root,'scripts/render_report.mjs'),specPath,'--results',resultsPath,'--findings',findingsPath,'--judgments',fx('smoke-judgment-ledger.json'),'--confirmation',fx('smoke-confirmation.json'),'--brief',fx('smoke-execution-brief.json'),'--output',htmlPath],{encoding:'utf8'});
try{if(r.status!==0){process.stderr.write(r.stdout+r.stderr);throw new Error('render failed')}const html=fs.readFileSync(htmlPath,'utf8');for(const marker of ['dot-stem','benchmark','dumbbell-line','segment-0','heat-cell','box-fill','bubble'])if(!html.includes(marker))throw new Error(`missing ${marker}`);console.log('PASS chart types v3');}finally{fs.rmSync(temp,{recursive:true,force:true})}
