#!/usr/bin/env node
import fs from 'node:fs';import os from 'node:os';import path from 'node:path';import {spawnSync} from 'node:child_process';import {fileURLToPath} from 'node:url';
const root=path.dirname(path.dirname(fileURLToPath(import.meta.url))),runDir=fs.mkdtempSync(path.join(os.tmpdir(),'quanti-report-test-')),fx=n=>path.join(root,'evals/fixtures',n);
const run=(script,args,expected=0)=>{const r=spawnSync(process.execPath,[path.join(root,'scripts',script),...args],{encoding:'utf8'});if(r.status!==expected){process.stderr.write(r.stdout+r.stderr);throw new Error(`${script} returned ${r.status}; expected ${expected}`)}};
try{
  const smokeResults=JSON.parse(fs.readFileSync(fx('smoke-analysis-results.json'),'utf8'));
  const profile={schema_version:'1.1',input:'fixture',snapshot:{sha256:smokeResults.input.data_snapshot_sha256,bytes:0},row_count:8,column_count:2,columns:[{name:'channel',non_null:8,missing:0,inferred_type:'string'}]};fs.writeFileSync(path.join(runDir,'data-profile.json'),JSON.stringify(profile));
  const copies=[['smoke-execution-brief.json','execution-brief.json'],['smoke-analysis-results.json','analysis-results.json'],['smoke-findings-ledger.json','findings-ledger.json'],['smoke-judgment-ledger.json','judgment-ledger.json'],['smoke-report-spec.json','report-spec.json']];for(const [a,b] of copies)fs.copyFileSync(fx(a),path.join(runDir,b));
  run('validate_run.mjs',[runDir,'--stage','design']);run('validate_run.mjs',[runDir,'--stage','preflight']);run('render_run.mjs',[runDir]);run('validate_run.mjs',[runDir,'--stage','final']);
  const html=fs.readFileSync(path.join(runDir,'analysis-report.html'),'utf8'),md=fs.readFileSync(path.join(runDir,'analysis-report.md'),'utf8');if(!html.includes('chart-reading-guide')||!html.includes('data-finding-id="scale-finding"')||!md.includes('怎么看：'))throw new Error('Unified rendering failed');
  const bad=JSON.parse(fs.readFileSync(fx('smoke-findings-ledger.json'),'utf8'));bad.findings[0].result_refs=['missing-result'];fs.writeFileSync(path.join(runDir,'findings-ledger.json'),JSON.stringify(bad));run('validate_run.mjs',[runDir,'--stage','preflight'],1);
  fs.copyFileSync(fx('smoke-findings-ledger.json'),path.join(runDir,'findings-ledger.json'));run('render_run.mjs',[runDir]);run('validate_run.mjs',[runDir,'--stage','final']);
  const classBrief=JSON.parse(fs.readFileSync(fx('smoke-execution-brief.json'),'utf8'));classBrief.method_plan.secondary_methods=['segmentation-classification'];const briefText=JSON.stringify(classBrief);fs.writeFileSync(path.join(runDir,'execution-brief.json'),briefText);const crypto=await import('node:crypto'),briefHash=crypto.createHash('sha256').update(briefText).digest('hex');const classResults=JSON.parse(fs.readFileSync(fx('smoke-analysis-results.json'),'utf8'));classResults.input.execution_brief_sha256=briefHash;fs.writeFileSync(path.join(runDir,'analysis-results.json'),JSON.stringify(classResults));run('validate_run.mjs',[runDir,'--stage','preflight'],1);
  const audit={schema_version:'1.0',sample_plan:'每类边界与随机样本',first_review:[{class_id:'a',sample_size:5,error_count:1,notes:'一次复核'}],second_review:[{class_id:'a',sample_size:5,error_count:0,notes:'二次复核'}],disagreements:['一条边界样本'],revision_impact:'修正规则后规模变化有限',status:'exploratory'};fs.writeFileSync(path.join(runDir,'classification-audit.json'),JSON.stringify(audit));run('validate_run.mjs',[runDir,'--stage','preflight'],1);
  console.log(`PASS v3 pipeline (CP0 + canonical findings + preflight + render + final fingerprints)\nARTIFACT_DIR=${runDir}`);
}catch(error){fs.rmSync(runDir,{recursive:true,force:true});throw error}
